[tasks.default]
    deps = ["packages", "initialconfig", "kernel"]

[tasks.packages]
     cmds = [
        ["@install", "yay"],
        ["@install_aur", "gnome-flashback"],
        ["@install_aur", "i3-gaps"],
        ["@install_aur", "i3-gnome"],
        ["@install_aur", "i3status"],
        ["@install_aur", "i3exit"],
        ["@install_aur", "i3-resurrect"],
        ["@install_aur", "rofi"],
        ["@install_aur", "rofi-bluetooth-git"],
        ["@install_aur", "seahorse"],
        ["@install_aur", "terminator"],
        ["@install_aur", "network-manager-applet"],
        ["@install_aur", "xorg-xev"],
        ["@install_aur", "xcape"],
        ["@remove", "gnome-user-share"],
        ["@remove", "mod_dnssd"],
        ["@remove", "apache"],
    ]


[tasks.packages_extra]
     cmds = [
        ["@install_aur", "signal-desktop"],
        ["@install_aur", "enpass-bin"],
    ]

[tasks.initialconfig]   
    links = [
        [".config/i3/config"],
        [".config/i3/i3status/i3status.conf"],
        [".config/rofi/config.rasi"]
    ]
    cmds = [
        ["@install_aur", "rslsync"],
        ["mkdir","-p", "~/Sync/downloads"],
        ["dconf", "write", "/org/gnome/gnome-flashback/desktop","false"],
        ["dconf", "write", "/org/gnome/gnome-flashback/root-background","true"]
    ]

[tasks.resilio]
    rejects = [["test", "-d", ".config/rslsync"]]    
    templates = [
        [".config/rslsync/rslsync.conf"]
    ]
    cmds = [
        ["mkdir","-p","${HM_DEST}/.config/rslsync/.sync"],
        ["systemctl","--user","enable","rslsync"],
        ["systemctl","--user","restart","rslsync"],
    ]

[tasks.kernel]
    cmds = [
        ["sudo","mhwd-kernel", "-i", "linux59"]
    ]
    
[macros.install]
    prefix = ["sudo", "pacman", "-S", "--needed", "--noconfirm"] 

[macros.install_aur]
    prefix = ["yay", "-S", "--needed", "--answerclean","No","--answerdiff","N","--answerupgrade","No"]    

[macros.remove]
    prefix = ["yay", "-R","--noconfirm"]
